# screen Configuration
screen_home       = 0
screen_project    = 1
screen_button     = 2
screen_wather     = 3
screen_sensor     = 4
screen_load_cell  = 5
screen_accelo     = 6
screen_gas_sensor = 7

# MQTT Configuration
MQTT_PORT = 1883
MQTT_TOPIC_MQTT_Rq     = "mqtt/request"
MQTT_TOPIC_MQTT_Rs     = "mqtt/response"
MQTT_TOPIC_LED      = "arduino/Led"
MQTT_TOPIC_SENSOR   = "arduino/sensor"
MQTT_TOPIC_CONTROL  = "arduino/sensor"
MQTT_TOPIC_WATHER   = "arduino/Weather"
MQTT_TOPIC_ALERTS   = "alerts/weather"
MQTT_TOPIC_LOADCELL = "arduino/LoadCell"
MQTT_TOPIC_MPU6050  = "arduino/MPU6050"
MQTT_TOPIC_GAS      = "arduino/gas"

# Keyboard Configuration
Password_BTN_PasswordAccueiltext = ""
Password_BTN_PasswordAtext = ("A", "a", "1")
Password_EDB_Passwordtext = ""
Password_BTN_PasswordZtext = ("Z" ,"z", "2")
Password_BTN_PasswordEtext = ("E", "e", "3")
Password_BTN_PasswordRtext = ("R", "r", "4")
Password_BTN_PasswordTtext = ("T", "t", "5")
Password_BTN_PasswordYtext = ("Y", "y", "6")
Password_BTN_PasswordUtext = ("U", "u", "7")
Password_BTN_PasswordItext = ("I", "i", "8")
Password_BTN_PasswordOtext = ("O", "o", "9")
Password_BTN_PasswordPtext = ("P", "p", "0")
Password_BTN_PasswordQtext = ("Q", "q", "@")
Password_BTN_PasswordStext = ("S", "s", "#")
Password_BTN_PasswordDtext = ("D", "d", "%")
Password_BTN_PasswordFtext = ("F", "f", "&&")
Password_BTN_PasswordGtext = ("G", "g", "*")
Password_BTN_PasswordHtext = ("H", "h", "-")
Password_BTN_PasswordJtext = ("J", "j", "+")
Password_BTN_PasswordKtext = ("K", "k", "(")
Password_BTN_PasswordLtext = ("L", "l", ")")
Password_BTN_PasswordMtext = ("M", "m", ";")
Password_BTN_PasswordWtext = ("W", "w", "!")
Password_BTN_PasswordXtext = ("X", "x", '"')
Password_BTN_PasswordCtext = ("C", "c", "<")
Password_BTN_PasswordVtext = ("V", "v", ">")
Password_BTN_PasswordBtext = ("B", "b", "'")
Password_BTN_PasswordNtext = ("N", "n", ":")
Password_BTN_PasswordCommatext = (",", "?", ":")
Password_BTN_PasswordDottext = (".", ";", "$")
Password_BTN_PasswordSltext = ("/", "\ ", "~")
Password_BTN_PasswordUstext = ("_", "=", "^")
Password_BTN_Password1text = "1"
Password_BTN_Password2text = "2"
Password_BTN_Password3text = "3"
Password_BTN_Password4text = "4"
Password_BTN_Password5text = "5"
Password_BTN_Password6text = "6"
Password_BTN_Password7text = "7"
Password_BTN_Password8text = "8"
Password_BTN_Password9text = "9"
Password_BTN_Password0text = "0"
Password_BTN_PasswordTicktext = ""
Password_BTN_PasswordCrosstext = ""
Password_BTN_PasswordRetourtext = ""